// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56GXZMKdW-0t40E4zeIh38_O1MG_JUp0',
    appId: '1:888847569168:web:5033d1fa58bafc9cff1595',
    messagingSenderId: '888847569168',
    projectId: 'ai-resume-scanner-eb079',
    authDomain: 'ai-resume-scanner-eb079.firebaseapp.com',
    storageBucket: 'ai-resume-scanner-eb079.firebasestorage.app',
    measurementId: 'G-3D7JVSZ333',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQeGYS8h9d1VZ_YrKJffFPMgoK1yKTEyE',
    appId: '1:888847569168:android:0e3586da2fb19abfff1595',
    messagingSenderId: '888847569168',
    projectId: 'ai-resume-scanner-eb079',
    storageBucket: 'ai-resume-scanner-eb079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj1Y4bL6A1k3pOYj8V2XKsxHBIvc5rmbs',
    appId: '1:888847569168:ios:f314d21566c441b6ff1595',
    messagingSenderId: '888847569168',
    projectId: 'ai-resume-scanner-eb079',
    storageBucket: 'ai-resume-scanner-eb079.firebasestorage.app',
    iosBundleId: 'com.bilalblouchg786.aiResumeScanner',
  );
}
